"""add personal_problem table

Revision ID: 48f3d38c42df
Revises: 13f24ef8cf51
Create Date: 2025-07-08 00:44:37.068613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48f3d38c42df'
down_revision = '13f24ef8cf51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('personal_problem')
    # ### end Alembic commands ###
