"""Add options and correct columns to Problem

Revision ID: 8570220d4dd6
Revises: bc7ad14586f8
Create Date: 2025-08-26 20:31:07.580925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8570220d4dd6'
down_revision = 'bc7ad14586f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('correct', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('correct')
        batch_op.drop_column('options')

    # ### end Alembic commands ###
