"""Add word_content and latex_content fields

Revision ID: bc7ad14586f8
Revises: 1bedac9f70b4
Create Date: 2025-07-26 02:53:10.571685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7ad14586f8'
down_revision = '1bedac9f70b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('latex_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('latex_content')
        batch_op.drop_column('word_content')

    # ### end Alembic commands ###
